<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'JrvZf2SimpleMvc\Module'                      => __DIR__ . '/Module.php',
  'JrvZf2SimpleMvc\Controller\SimpleController' => __DIR__ . '/src/JrvZf2SimpleMvc/Controller/SimpleController.php',
  'JrvZf2SimpleMvc\Exception\SimpleMvcException'      => __DIR__ . '/src/JrvZf2SimpleMvc/Exception/SimpleMvcException.php',
);
